-- MySQL Script generated by MySQL Workbench
-- Fri Mar 28 17:16:16 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema betlearn
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema betlearn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `betlearn` DEFAULT CHARACTER SET utf8 ;
USE `betlearn` ;

-- -----------------------------------------------------
-- Table `betlearn`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betlearn`.`Users` (
  `id_user` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(100) NOT NULL,
  `user_email` VARCHAR(100) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `birthdate` DATE NOT NULL,
  `money` DECIMAL(10,2) UNSIGNED NOT NULL,
  `points` INT UNSIGNED NOT NULL,
  `profile_image` VARCHAR(200) NULL,
  `bets_visibility` TINYINT NOT NULL DEFAULT 1,
  `tutorial_verification` TINYINT NOT NULL,
  `password` TEXT(100) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `email_utilizador_UNIQUE` (`user_email` ASC) ,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) ,
  UNIQUE INDEX `id_UNIQUE` (`id_user` ASC) ,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betlearn`.`Challenges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betlearn`.`Challenges` (
  `id_challenge` INT NOT NULL AUTO_INCREMENT,
  `challenge_number` INT UNSIGNED NOT NULL,
  `challenge_name` VARCHAR(50) NOT NULL,
  `short_description` VARCHAR(100) NOT NULL,
  `long_description` VARCHAR(150) NOT NULL,
  `image` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_challenge`),
  UNIQUE INDEX `id_UNIQUE` (`id_challenge` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betlearn`.`User_has_Challenges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betlearn`.`User_has_Challenges` (
  `ref_id_user` INT NOT NULL,
  `ref_id_challenge` INT NOT NULL,
  `challenge_completed` TINYINT NOT NULL,
  `challenge_blocked` TINYINT NOT NULL,
  `challenge_detail_seen` TINYINT NOT NULL,
  `progress_percentage` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`ref_id_user`, `ref_id_challenge`),
  INDEX `fk_Utilizadores_has_Desafios_Desafios1_idx` (`ref_id_challenge` ASC) ,
  INDEX `fk_Utilizadores_has_Desafios_Utilizadores_idx` (`ref_id_user` ASC) ,
  UNIQUE INDEX `id_utilizador_UNIQUE` (`ref_id_user` ASC) ,
  CONSTRAINT `fk_Utilizadores_has_Desafios_Utilizadores`
    FOREIGN KEY (`ref_id_user`)
    REFERENCES `betlearn`.`Users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilizadores_has_Desafios_Desafios1`
    FOREIGN KEY (`ref_id_challenge`)
    REFERENCES `betlearn`.`Challenges` (`id_challenge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betlearn`.`Questionnaire_Response`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betlearn`.`Questionnaire_Response` (
  `id_questionnaire_response` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `budget` DECIMAL(10,2) UNSIGNED NOT NULL,
  `verification` TINYINT NOT NULL DEFAULT 0,
  `salary_answer` INT UNSIGNED NOT NULL,
  `expenses_answer` INT UNSIGNED NOT NULL,
  `available_amount_answer` INT UNSIGNED NOT NULL,
  `debt_boolean_answer` TINYINT UNSIGNED NOT NULL,
  `debt_monthly_value` DECIMAL(10,2) UNSIGNED NOT NULL,
  `income_source_answer` INT UNSIGNED NOT NULL,
  `ref_id_user` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_questionnaire_response`),
  UNIQUE INDEX `id_UNIQUE` (`id_questionnaire_response` ASC) ,
  INDEX `fk_Respostas_Questionario_Utilizadores1_idx` (`ref_id_user` ASC) ,
  CONSTRAINT `fk_Respostas_Questionario_Utilizadores1`
    FOREIGN KEY (`ref_id_user`)
    REFERENCES `betlearn`.`Users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betlearn`.`Games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betlearn`.`Games` (
  `id_game` INT NOT NULL AUTO_INCREMENT,
  `local_team` VARCHAR(50) NOT NULL,
  `visitor_team` VARCHAR(50) NOT NULL,
  `schedule` DATETIME NOT NULL,
  `betted_team` VARCHAR(50) NOT NULL,
  `odd` DECIMAL(10,2) UNSIGNED NOT NULL,
  `goals_local_team` INT UNSIGNED NOT NULL,
  `goals_visitor_team` INT UNSIGNED NOT NULL,
  `image` VARCHAR(200) NOT NULL,
  `game_state` TINYINT NOT NULL,
  PRIMARY KEY (`id_game`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betlearn`.`Tips`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betlearn`.`Tips` (
  `id_tip` INT NOT NULL AUTO_INCREMENT,
  `tip` VARCHAR(50) NOT NULL,
  `active` INT NOT NULL,
  PRIMARY KEY (`id_tip`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betlearn`.`Bets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betlearn`.`Bets` (
  `id_bet` INT NOT NULL AUTO_INCREMENT,
  `bet_date` DATETIME NOT NULL,
  `bet_type` TINYINT NOT NULL,
  `amount` DECIMAL(10,2) UNSIGNED NOT NULL,
  `potential_earning` DECIMAL(10,2) UNSIGNED NOT NULL,
  `odd` DECIMAL(10,2) UNSIGNED NOT NULL,
  `bet_ref` INT UNSIGNED NOT NULL,
  `bet_state` TINYINT NOT NULL COMMENT 'Ativa/Encerrada',
  `bet_result` TINYINT NOT NULL,
  `ref_id_user` INT NOT NULL,
  PRIMARY KEY (`id_bet`),
  INDEX `fk_Apostas_Utilizadores1_idx` (`ref_id_user` ASC) ,
  CONSTRAINT `fk_Apostas_Utilizadores1`
    FOREIGN KEY (`ref_id_user`)
    REFERENCES `betlearn`.`Users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betlearn`.`Championship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betlearn`.`Championship` (
  `id_championship` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `json` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_championship`),
  UNIQUE INDEX `json_UNIQUE` (`json` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betlearn`.`Bets_has_Games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betlearn`.`Bets_has_Games` (
  `ref_id_bet` INT NOT NULL,
  `ref_id_game` INT NOT NULL,
  `ref_id_championship` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ref_id_bet`, `ref_id_game`, `ref_id_championship`),
  INDEX `fk_Apostas_has_Jogos_Jogos1_idx` (`ref_id_game` ASC) ,
  INDEX `fk_Apostas_has_Jogos_Apostas1_idx` (`ref_id_bet` ASC) ,
  INDEX `fk_Apostas_has_Jogos_Campeonatos1_idx` (`ref_id_championship` ASC) ,
  CONSTRAINT `fk_Apostas_has_Jogos_Apostas1`
    FOREIGN KEY (`ref_id_bet`)
    REFERENCES `betlearn`.`Bets` (`id_bet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Apostas_has_Jogos_Jogos1`
    FOREIGN KEY (`ref_id_game`)
    REFERENCES `betlearn`.`Games` (`id_game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Apostas_has_Jogos_Campeonatos1`
    FOREIGN KEY (`ref_id_championship`)
    REFERENCES `betlearn`.`Championship` (`id_championship`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betlearn`.`Step_Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betlearn`.`Step_Video` (
  `id_step_video` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `step_video_url` VARCHAR(200) NOT NULL,
  `step_video_description` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_step_video`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betlearn`.`Step_Bet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betlearn`.`Step_Bet` (
  `id_step_bet` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `step_bet_description` VARCHAR(200) NOT NULL,
  `step_bet_json` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_step_bet`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betlearn`.`Step_Questionnaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betlearn`.`Step_Questionnaire` (
  `id_step_questionnaire` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `step_questionnaire_description` VARCHAR(200) NOT NULL,
  `step_questionnaire_json` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_step_questionnaire`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betlearn`.`Step_View`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betlearn`.`Step_View` (
  `id_step_view` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `step_view_description` VARCHAR(200) NOT NULL,
  `step_view_page` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_step_view`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betlearn`.`Steps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betlearn`.`Steps` (
  `id_step` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ref_id_step_video` INT NULL,
  `ref_id_step_bet` INT UNSIGNED NULL,
  `ref_id_step_view` INT NULL,
  `ref_id_step_questionnaire` INT UNSIGNED NULL,
  `ref_id_challenges` INT NOT NULL,
  PRIMARY KEY (`id_step`),
  INDEX `fk_Steps_Step_Video1_idx` (`ref_id_step_video` ASC) ,
  INDEX `fk_Steps_Step_Bet1_idx` (`ref_id_step_bet` ASC) ,
  INDEX `fk_Steps_Step_View1_idx` (`ref_id_step_view` ASC) ,
  INDEX `fk_Steps_Step_Questionnaire1_idx` (`ref_id_step_questionnaire` ASC) ,
  INDEX `fk_Steps_Challenges1_idx` (`ref_id_challenges` ASC) ,
  CONSTRAINT `fk_Steps_Step_Video1`
    FOREIGN KEY (`ref_id_step_video`)
    REFERENCES `betlearn`.`Step_Video` (`id_step_video`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Steps_Step_Bet1`
    FOREIGN KEY (`ref_id_step_bet`)
    REFERENCES `betlearn`.`Step_Bet` (`id_step_bet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Steps_Step_View1`
    FOREIGN KEY (`ref_id_step_view`)
    REFERENCES `betlearn`.`Step_View` (`id_step_view`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Steps_Step_Questionnaire1`
    FOREIGN KEY (`ref_id_step_questionnaire`)
    REFERENCES `betlearn`.`Step_Questionnaire` (`id_step_questionnaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Steps_Challenges1`
    FOREIGN KEY (`ref_id_challenges`)
    REFERENCES `betlearn`.`Challenges` (`id_challenge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betlearn`.`User_has_Challenges_has_Steps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betlearn`.`User_has_Challenges_has_Steps` (
  `ref_user_has_Challenges_id_user` INT NOT NULL,
  `ref_user_has_Challenges_id_challenge` INT NOT NULL,
  `ref_id_steps` INT UNSIGNED NOT NULL,
  `state` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ref_user_has_Challenges_id_user`, `ref_user_has_Challenges_id_challenge`, `ref_id_steps`),
  INDEX `fk_User_has_Challenges_has_Steps_Steps1_idx` (`ref_id_steps` ASC) ,
  INDEX `fk_User_has_Challenges_has_Steps_User_has_Challenges1_idx` (`ref_user_has_Challenges_id_user` ASC, `ref_user_has_Challenges_id_challenge` ASC) ,
  CONSTRAINT `fk_User_has_Challenges_has_Steps_User_has_Challenges1`
    FOREIGN KEY (`ref_user_has_Challenges_id_user` , `ref_user_has_Challenges_id_challenge`)
    REFERENCES `betlearn`.`User_has_Challenges` (`ref_id_user` , `ref_id_challenge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Challenges_has_Steps_Steps1`
    FOREIGN KEY (`ref_id_steps`)
    REFERENCES `betlearn`.`Steps` (`id_step`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `betlearn`.`Admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `betlearn`.`Admins` (
  `id_admin` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_admin`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) ,
  UNIQUE INDEX `id_admin_UNIQUE` (`id_admin` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
