# Nome da Pipeline
name: Preview_&_Build_API

# Ocasioes em que o workflow comeca a trabalhar
on:
  push: # Em qualquer commit para ca feito na main
    branches:
      - main || Pipeline

# Jobs a ser executados
jobs:
  deploy-vercel-preview:
    name: Deploy do Vercel em Preview
    runs-on: ubuntu-latest
    steps:
      - name: Analisar Repositorio
        uses: actions/checkout@v4

      - name: Setup do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"

      - name: Instalar as Dependencias
        run: npm install
        working-directory: betlearn_backend

      - name: Instalar CLI da Vercel
        run: npm install --global vercel@latest
        working-directory: betlearn_backend

      - name: Pull Env Vercel
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
        working-directory: betlearn_backend

      - name: Build Vercel
        run: |
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
          vercel build --token=${{ secrets.VERCEL_ACCESS_TOKEN}}
        working-directory: betlearn_backend

      - name: Deploy Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
        working-directory: betlearn_backend

  deploy-vercel-production:
    name: Deploy do Vercel em Producao
    needs: deploy-vercel-preview
    runs-on: ubuntu-latest
    steps:
      - name: Analisar Repositorio
        uses: actions/checkout@v4

      - name: Instalar CLI da Vercel
        run: npm install --global vercel@latest
        working-directory: betlearn_backend

      - name: Pull Env Vercel
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
        working-directory: betlearn_backend

      - name: Build Vercel
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
        working-directory: betlearn_backend

      - name: Deploy Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
        working-directory: betlearn_backend
